# Generated by Django 2.2.5 on 2019-09-18 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='authors',
        ),
        migrations.AddField(
            model_name='citation',
            name='authors',
            field=models.ForeignKey(default=1, help_text='Szerzők', on_delete=django.db.models.deletion.PROTECT, to='exams.Author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
