# Generated by Django 2.2.5 on 2019-09-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20190918_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='authors',
        ),
        migrations.AddField(
            model_name='citation',
            name='authors',
            field=models.ManyToManyField(help_text='Szerzők', to='exams.Author'),
        ),
    ]
