# Generated by Django 2.2.5 on 2019-09-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20190918_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='exams.Place'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='exams.Year'),
        ),
    ]
