# Generated by Django 2.2.7 on 2019-11-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_auto_20191025_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
