# Generated by Django 2.2.7 on 2019-11-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_problem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
